/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalhot1;

import javax.swing.JOptionPane;

/**
 *
 * @author Professor
 */
public class FormTurma extends javax.swing.JFrame {    
    Estrutura e;

    /**
     * Creates new form FormTurma
     */
    public FormTurma() {
        initComponents();
        int qtdeAlunos = Integer.parseInt(JOptionPane.showInputDialog("Digite a quantidade de alunos"));
        e = new Estrutura(qtdeAlunos);
        
        DesabilitaBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNotaExercicio = new javax.swing.JTextField();
        txtNotaTrabalho = new javax.swing.JTextField();
        txtNotaProva = new javax.swing.JTextField();
        btnSalvarAluno = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnRelatorioAlunos = new javax.swing.JButton();
        btnNumeroAlunosAprovados = new javax.swing.JButton();
        btnNumeroAlunosReprovados = new javax.swing.JButton();
        btnNumeroAlunosRecuperacao = new javax.swing.JButton();
        btnMediaTurma = new javax.swing.JButton();
        btnMaiorNota = new javax.swing.JButton();
        btnMenorNota = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turma de ADS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Turma de ADS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nota de Exercício:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nota de Trabalho:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nota de Prova:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtNotaExercicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtNotaTrabalho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtNotaProva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnSalvarAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalvarAluno.setText("Salvar Aluno");
        btnSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlunoActionPerformed(evt);
            }
        });

        btnRelatorioAlunos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRelatorioAlunos.setText("Relatório de Alunos");
        btnRelatorioAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioAlunosActionPerformed(evt);
            }
        });

        btnNumeroAlunosAprovados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNumeroAlunosAprovados.setText("Número de Alunos Aprovados");
        btnNumeroAlunosAprovados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroAlunosAprovadosActionPerformed(evt);
            }
        });

        btnNumeroAlunosReprovados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNumeroAlunosReprovados.setText("Número de Alunos Reprovados");
        btnNumeroAlunosReprovados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroAlunosReprovadosActionPerformed(evt);
            }
        });

        btnNumeroAlunosRecuperacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNumeroAlunosRecuperacao.setText("Número de Alunos em Recuperação");
        btnNumeroAlunosRecuperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroAlunosRecuperacaoActionPerformed(evt);
            }
        });

        btnMediaTurma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMediaTurma.setText("Média da Turma");
        btnMediaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaTurmaActionPerformed(evt);
            }
        });

        btnMaiorNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMaiorNota.setText("Maior Nota (Nome + Nota)");
        btnMaiorNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaiorNotaActionPerformed(evt);
            }
        });

        btnMenorNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMenorNota.setText("Menor Nota (Nome + Nota)");
        btnMenorNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorNotaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setText("Peso: 0.2 ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setText("Peso: 0.3 ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setText("Peso: 0.5 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvarAluno)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNotaProva, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNotaTrabalho, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNotaExercicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRelatorioAlunos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNumeroAlunosAprovados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNumeroAlunosReprovados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNumeroAlunosRecuperacao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnMediaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMaiorNota, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenorNota, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNotaExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNotaTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNotaProva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvarAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorioAlunos)
                    .addComponent(btnNumeroAlunosAprovados)
                    .addComponent(btnNumeroAlunosReprovados)
                    .addComponent(btnNumeroAlunosRecuperacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMediaTurma)
                    .addComponent(btnMaiorNota)
                    .addComponent(btnMenorNota))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DesabilitaCampos()
    {
        txtNome.setEnabled(false);
        txtNotaExercicio.setEnabled(false);
        txtNotaProva.setEnabled(false);
        txtNotaTrabalho.setEnabled(false);
        btnSalvarAluno.setEnabled(false);
    }
    
    private void HabilitaBotoes()
    {
        btnRelatorioAlunos.setEnabled(true);
        btnNumeroAlunosAprovados.setEnabled(true);
        btnNumeroAlunosReprovados.setEnabled(true);
        btnNumeroAlunosRecuperacao.setEnabled(true);
        btnMediaTurma.setEnabled(true);
        btnMaiorNota.setEnabled(true);
        btnMenorNota.setEnabled(true);
    }
    
    private void DesabilitaBotoes()
    {
        btnRelatorioAlunos.setEnabled(false);
        btnNumeroAlunosAprovados.setEnabled(false);
        btnNumeroAlunosReprovados.setEnabled(false);
        btnNumeroAlunosRecuperacao.setEnabled(false);
        btnMediaTurma.setEnabled(false);
        btnMaiorNota.setEnabled(false);
        btnMenorNota.setEnabled(false);
    }
    
    private void btnSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlunoActionPerformed
        
        try
        {    
            if (!txtNome.equals(""))
            {
                double nE = Double.parseDouble(txtNotaExercicio.getText());
                if (nE > 10 || nE < 0)
                {
                    JOptionPane.showMessageDialog(null, "Nota exercicio Inválido");
                    txtNotaExercicio.setText("");
                    txtNotaExercicio.requestFocus();
                    return;
                }
                double nT = Double.parseDouble(txtNotaTrabalho.getText());
                if (nT > 10 || nT < 0)
                {
                    JOptionPane.showMessageDialog(null, "Nota trabalho Inválido");
                    txtNotaTrabalho.setText("");
                    txtNotaTrabalho.requestFocus();
                    return;
                }
                double nP = Double.parseDouble(txtNotaProva.getText());
                if (nP > 10 || nP < 0)
                {
                    JOptionPane.showMessageDialog(null, "Nota prova Inválido");
                    txtNotaProva.setText("");
                    txtNotaProva.requestFocus();
                    return;
                }
        
        
                e.insert(txtNome.getText().toUpperCase(),nP,nT,nE);
        
                txtNome.setText("");
                txtNotaExercicio.setText("");
                txtNotaProva.setText("");
                txtNotaTrabalho.setText("");
        
                txtNome.requestFocus();
        
                JOptionPane.showMessageDialog(null,"Dados do Aluno inseridos com Sucesso !");
            }
        }
        catch(Exception exc)
        {
            JOptionPane.showMessageDialog(null, "É necessário preencher todos os campos !\n" + exc);  
        }
        if (e.size() == e.indice())
        {
            DesabilitaCampos();
            HabilitaBotoes();
        }
    }//GEN-LAST:event_btnSalvarAlunoActionPerformed

    private void btnMediaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaTurmaActionPerformed
        JOptionPane.showMessageDialog(null, "[Media da turma]:\n\n" + "         " + Double.toString(e.getMediaTurma()));
    }//GEN-LAST:event_btnMediaTurmaActionPerformed

    private void btnNumeroAlunosAprovadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroAlunosAprovadosActionPerformed
        JOptionPane.showMessageDialog(null, "[Alunos Aprovados]:\n" + e.getAlunoAprovado() + 
                "\n\n                                    Total = " + Integer.toString(e.getAprovado()));
    }//GEN-LAST:event_btnNumeroAlunosAprovadosActionPerformed

    private void btnNumeroAlunosReprovadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroAlunosReprovadosActionPerformed
        JOptionPane.showMessageDialog(null, "[Alunos Reprovados]:\n" + e.getAlunoReprovado() + 
                "\n\n                                     Total = " + Integer.toString(e.getReprovado()));
    }//GEN-LAST:event_btnNumeroAlunosReprovadosActionPerformed

    private void btnNumeroAlunosRecuperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroAlunosRecuperacaoActionPerformed
        JOptionPane.showMessageDialog(null, "[Alunos de Recuperação:]\n" + e.getAlunoRecuperacao() + 
                "\n\n                                        Total = " + Integer.toString(e.getRecuperacao()));
    }//GEN-LAST:event_btnNumeroAlunosRecuperacaoActionPerformed

    private void btnMaiorNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaiorNotaActionPerformed
        JOptionPane.showMessageDialog(null, "[Aluno que obteve a MAIOR nota]:\n\n" + e.getMaiorNota());
    }//GEN-LAST:event_btnMaiorNotaActionPerformed

    private void btnMenorNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorNotaActionPerformed
        JOptionPane.showMessageDialog(null, "[Aluno que obteve a MENOR nota]:\n\n" + e.getMenorNota());
    }//GEN-LAST:event_btnMenorNotaActionPerformed

    private void btnRelatorioAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioAlunosActionPerformed
        JOptionPane.showMessageDialog(null, "[Aluno]:                           [Nota]:\n\n" + e.getRelatorio());
    }//GEN-LAST:event_btnRelatorioAlunosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaiorNota;
    private javax.swing.JButton btnMediaTurma;
    private javax.swing.JButton btnMenorNota;
    private javax.swing.JButton btnNumeroAlunosAprovados;
    private javax.swing.JButton btnNumeroAlunosRecuperacao;
    private javax.swing.JButton btnNumeroAlunosReprovados;
    private javax.swing.JButton btnRelatorioAlunos;
    private javax.swing.JButton btnSalvarAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNotaExercicio;
    private javax.swing.JTextField txtNotaProva;
    private javax.swing.JTextField txtNotaTrabalho;
    // End of variables declaration//GEN-END:variables
}